### ISSUE TITLE
SetNullChildCache needs to clear Child from CNodes vector

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGen#185]
- [ ] Criteria 1

### Criteria 1
**Given:**
* A cache with a child

**When:**
* The child cache is set to null

**Then:**
* The child should be deleted from the CNodes vector

**Comment by jleidel** [comment]
Instead of clearing the entire CNodes vector, I suggest we use `DeleteChild(CoreGenNode *N)`

**Comment by fconlon** [comment]
That makes sense. I see you pushed a commit to fix this. The tests seem to have passed (I haven't seen a build fail in my inbox) so I'll close this issue.
