### ISSUE TITLE
CoreGenPortal Needs to be able to set the width of a register

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGen#187]

**Comment by jleidel** [comment]
I'll get this implemented.  Will add the following function to the CoreGenReg class: 

`SetWidth(unsigned width)`

**Comment by jleidel** [comment]
Correction, the function prototype will be: 
`SetWidth(int width)`

**Comment by fconlon** [comment]
Sounds good. I'm working from home for USAA today and I'm waiting on review/merge request approval. I'm going to get some work done on the portal while I'm waiting.

**Comment by jleidel** [comment]
passed all devel tests
