### ISSUE TITLE
UI Facilitation

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGen#189]
Branch for changes to facilitate the UI

**Comment by fconlon** [comment]
I will close this once I get everything rebased into devel and tested. Right now the uifacilitation branch works with the Portal for adding and editing all node types except plugins and instruction formats.

**Comment by jleidel** [comment]
> I will close this once I get everything rebased into devel and tested. Right now the uifacilitation branch works with the Portal for adding and editing all node types except plugins and instruction formats.

Is this complete?

**Comment by jleidel** [comment]
closing this issue
