### ISSUE TITLE
Coren Error ：No return parameters

### ISSUE THREAD

**Issue by dingzex** [opensocsysarch/CoreGen#338]
Hello!
When testing and using Coren, when "cgcli -- IR basicrisc.yaml -- compiler" is made for example level1 / step10, the "error executing the llvm CodeGen:" is output. What is the reason?

**Comment by jleidel** [comment]
You need to be more specific.  What build options did you use, what where the EXACT command line options

**Comment by dingzex** [comment]
I did the test completely according to the tutorial:
cgcli Parameter reference help:
 Execution Options:
	--verify                              : Verify the IR and exit
	--pass                                : Run some or all of the IR passes
	--chisel                              : Run the Chisel codegen
	--compiler [Optional Version]         : Run the compiler codegen

ding@ding-Asip:~/SystemArchitect/CoreGenTutorials/LEVEL1/Step10$ cgcli -ir BasicRISC.yaml --verify
ding@ding-Asip:~/SystemArchitect/CoreGenTutorials/LEVEL1/Step10$ cgcli -ir BasicRISC.yaml --pass
ding@ding-Asip:~/SystemArchitect/CoreGenTutorials/LEVEL1/Step10$ cgcli -ir BasicRISC.yaml --chisel
ding@ding-Asip:~/SystemArchitect/CoreGenTutorials/LEVEL1/Step10$ cgcli -ir BasicRISC.yaml --compiler

Error executing the LLVM codegen: 
![2021-07-28 21-44-55 的屏幕截图](https://user-images.githubusercontent.com/11873758/127333213-43640270-3893-4c24-8cb8-fdef7a1cd459.png)

**Comment by jleidel** [comment]
Did you initialize the System Architect archive first?

**Comment by dingzex** [comment]
Yes, I have run:
cgcli --init archive/master.yaml

**Comment by dingzex** [comment]
After I create html and man directories in Doxygen directory, it can be executed normally:

sudo make install

Then, perform the test tutorial:

Execute cgcli -- ir Basicrisc.yaml -- compiler

appear:

Error executing the LLVM codegen:

Without any prompt, the test process is terminated.

**Comment by dingzex** [comment]
1

**Comment by dingzex** [comment]
I wonder if you will continue to improve this project?
