### ISSUE TITLE
Installation instructions against Ubuntu 18.04

### ISSUE THREAD

**Issue by dahooz** [opensocsysarch/CoreGen#343]
## Intended result
Follow the installation instructions and get a working cgcli

## Actual result
Some bugs along the flow:

### Typo in LLVM repo name:
[Instructions say:](https://github.com/opensocsysarch/CoreGen#ubuntu-1804-bionic)
```bash
sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8.0 main"
```
But this leads to:
```
[...]
Err:15 https://apt.llvm.org/bionic llvm-toolchain-bionic-8.0 Release
  404  Not Found [IP: 2a04:4e42:1b::561 443]
[...]
E: The repository 'http://apt.llvm.org/bionic llvm-toolchain-bionic-8.0 Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Because the repo is actually sitting at:
```bash
sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main"
```

### missing instruction to install
[In the instructions](https://github.com/opensocsysarch/CoreGen#ubuntu-1804-bionic), the last step is `make`, but I could not find the binary in the build dir. I'd suggest to add a `make install` to the end of the instructions.

### `make install` error for documentation
When running make install, the build complains about the documentation not available:
```
$ make install
[...]
Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/***/CoreGenTemp/doxygen/html".


Makefile:116: recipe for target 'install' failed
make: *** [install] Error 1
```
I could fix thix by running `make doc` and then `make install` again. Maybe you want to add the `doc` target to the prerequisites of install?

*Thanks for your tutorial at DAC*

**Comment by jleidel** [comment]
LLVM recently moved their deb repos around.  We'll make the changes to the install instructions.  The `make doc` command requires Doxygen to be installed.  I'll add that the requirements.
